language: python

python:
  - "3.6"

before_install:
  - docker pull rabbitmq
  - docker run -d --hostname test-rabbit --name test-rabbit -p 5672:5672 -p 15672:15672 rabbitmq:3-management

install:
  - python setup.py install
  - pip install pytest

script:
  - pytest -s -v tests/default.py

notifications:
  webhooks:
    urls:
      - https://$WEBHOOK_USER:$WEBHOOK_PASSWORD@events.smetj.net/travis
